/*BANCO DATA MODIFICADA*/



CREATE DATABASE LIVRO
GO
USE [LIVRO];
GO
CREATE TABLE EDITORA (
CODIGO_EDITORA	   INT NOT NULL,
NOME_EDITORA       VARCHAR (50) NOT NULL,
ENDEREÇO           VARCHAR (80) NULL,
TELEFONE           VARCHAR (20) NULL,
E_MAIL             VARCHAR (50) NULL,
URL                VARCHAR (90) NULL,
);
GO
ALTER TABLE EDITORA
ADD CONSTRAINT XEDITORA 
PRIMARY KEY(CODIGO_EDITORA) ;
GO
CREATE TABLE AUTOR (
CODIGO_AUTOR	   INT NOT NULL,
NOME_AUTOR		   VARCHAR (50) NOT NULL
);
GO
ALTER TABLE AUTOR
ADD CONSTRAINT XAUTOR 
PRIMARY KEY (CODIGO_AUTOR) ;
GO
CREATE TABLE LIVRO (
CODIGO_LIVRO       INT NOT NULL,
CODIGO_CATEGORIA   INT NOT NULL,
NOME_LIVRO         VARCHAR (60) NOT NULL,
PRECO			   DECIMAL (14,2) NULL,
DATA_PUBLICACAO    DATE  NULL,
QUANTIDADE_EXEMPLAR    INT NOT NULL
);
GO
CREATE INDEX X1LIVRO ON LIVRO
(CODIGO_CATEGORIA);
GO
ALTER TABLE LIVRO
ADD CONSTRAINT XLIVRO 
PRIMARY KEY (CODIGO_LIVRO) ;
GO
CREATE TABLE CATEGORIA (
CODIGO_CATEGORIA   INT NOT NULL,
NOME_CATEGORIA	   VARCHAR (30) NOT NULL,
);
GO
ALTER TABLE CATEGORIA
ADD CONSTRAINT XCATEGORIA 
PRIMARY KEY (CODIGO_CATEGORIA);
GO
CREATE TABLE LIVRO_EDITORA (
CODIGO_EDITORA	   INT NOT NULL,
CODIGO_LIVRO	   INT NOT NULL
);
GO
CREATE INDEX X1LIVRO_EDITORA ON 
LIVRO_EDITORA
(CODIGO_LIVRO);
GO
CREATE INDEX X2LIVRO_EDITORA ON 
LIVRO_EDITORA
(CODIGO_EDITORA);
GO
ALTER TABLE LIVRO_EDITORA
ADD CONSTRAINT LIVRO_LIVRO_EDITORA
FOREIGN KEY (CODIGO_LIVRO)
REFERENCES LIVRO;
GO
ALTER TABLE LIVRO_EDITORA
ADD  CONSTRAINT EDITORA_LIVRO_EDITORA
FOREIGN KEY (CODIGO_EDITORA)
REFERENCES EDITORA;
GO
ALTER TABLE LIVRO_EDITORA
ADD CONSTRAINT XLIVRO_EDITORA 
PRIMARY KEY (CODIGO_LIVRO, CODIGO_EDITORA);
GO
CREATE TABLE LIVRO_AUTOR (
CODIGO_AUTOR	   INT NOT NULL,
CODIGO_LIVRO	   INT NOT NULL
);
GO
CREATE INDEX X1LIVRO_AUTOR 
ON LIVRO_AUTOR(CODIGO_LIVRO);
GO
CREATE INDEX X2LIVRO_AUTOR 
ON LIVRO_AUTOR(CODIGO_AUTOR);
GO
ALTER TABLE LIVRO_AUTOR
ADD CONSTRAINT XLIVRO_AUTOR 
PRIMARY KEY (CODIGO_LIVRO, CODIGO_AUTOR);
GO
CREATE TABLE CLIENTE(
CPF DECIMAL(18) NOT NULL,
NOME CHAR(40) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL
);
GO
ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CPF
PRIMARY KEY(CPF);
GO
CREATE TABLE FUNCIONARIO (
MATRICULA CHAR(10) NOT NULL,
NOME VARCHAR(50) NOT NULL,
GENERO CHAR(1) NOT NULL,
SALARIO DECIMAL(8,2) NOT NULL,
);
GO
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO
PRIMARY KEY(MATRICULA);
GO
CREATE TABLE VENDA (
CODIGO_VENDA		INT NOT NULL,
DATA				DATE NOT NULL,
TOTAL				DECIMAL (14,2) NOT NULL,
MATRICULA			CHAR(10) NOT NULL,
CPF					DECIMAL(18) NOT NULL
);
GO
CREATE INDEX CLIENTE_VENDA ON CLIENTE
(CPF);
GO
CREATE INDEX FUNCIONARIO_VENDA ON FUNCIONARIO
(MATRICULA);
GO
ALTER TABLE VENDA
ADD CONSTRAINT XVENDA 
PRIMARY KEY (CODIGO_VENDA);
GO
ALTER TABLE VENDA
ADD CONSTRAINT VENDA_FUNCIONARIO
FOREIGN KEY(MATRICULA)
REFERENCES FUNCIONARIO;
GO
ALTER TABLE VENDA
ADD CONSTRAINT VENDA_CLIENTE
FOREIGN KEY(CPF)
REFERENCES CLIENTE;
GO
CREATE TABLE ITEM_VENDA (
CODIGO_VENDA	   INT NOT NULL,
CODIGO_LIVRO	   INT NOT NULL,
VALOR			   DECIMAL (14,2) NOT NULL,
QUANTIDADE		   DECIMAL (10) NOT NULL
);
GO
CREATE INDEX XTITEM_VENDA ON VENDA
(CODIGO_VENDA);
GO
CREATE INDEX X1ITEM_VENDA ON LIVRO
(CODIGO_LIVRO);
GO
ALTER TABLE ITEM_VENDA
ADD  CONSTRAINT LIVRO_ITEM_VENDA
FOREIGN KEY (CODIGO_LIVRO)
REFERENCES LIVRO;
GO
ALTER TABLE ITEM_VENDA
ADD  CONSTRAINT VENDA_ITEM_VENDA
FOREIGN KEY (CODIGO_VENDA)
REFERENCES VENDA;
GO
ALTER TABLE ITEM_VENDA
ADD CONSTRAINT XZITEM_VENDA 
PRIMARY KEY (CODIGO_LIVRO,CODIGO_VENDA) ;
GO
ALTER TABLE LIVRO_AUTOR
ADD CONSTRAINT LIVRO_LIVRO_AUTOR
FOREIGN KEY (CODIGO_LIVRO)
REFERENCES LIVRO;
GO
ALTER TABLE LIVRO_AUTOR
ADD  CONSTRAINT AUTOR_LIVRO_AUTOR
FOREIGN KEY (CODIGO_AUTOR)
REFERENCES AUTOR;
GO
ALTER TABLE LIVRO
ADD  CONSTRAINT LIVRO_CATEGORIA
FOREIGN KEY (CODIGO_CATEGORIA)
REFERENCES CATEGORIA;

